//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GreatTracer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GREATTRACER_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDR_VIEW_MENU                   130
#define IDD_VIEW_DIALOG                 131
#define IDB_COLORAMP                    133
#define IDD_TX_DIALOG                   134
#define IDD_RX_DIALOG                   136
#define IDD_ANTE_DIALOG                 137
#define IDD_POLYGON_TX_DIALOG           138
#define IDD_POLYGON_RX_DIALOG           139
#define IDD_CALLOG_DIALOG               140
#define IDD_ENVIRONMENT                 142
#define IDC_LIST1                       1000
#define IDC_STATIC_X                    1001
#define IDC_STATIC_Y                    1002
#define IDC_STATIC_Z                    1003
#define IDC_RENDER                      1004
#define IDC_STATIC_FPS                  1005
#define IDC_STATIC_MINDB                1006
#define IDC_STATIC_MAXDB                1007
#define IDC_EDIT_DESCRIPTION            1008
#define IDC_EDIT_TX_HEIGHT              1009
#define IDC_EDIT_CARRIERFRE             1010
#define IDC_EDIT_INPUTPOWER             1011
#define IDC_EDIT_RX_PZ_DES              1013
#define IDC_EDIT__RX_PZ_Z               1014
#define IDC_STARTANGLE_EDIT             1015
#define IDC_ENDANGLE_EDIT               1016
#define IDC_POLYGON_HEIGHT_EDIT         1016
#define IDC_ANTEGAIN_EDIT               1017
#define IDC_POLYGON_SPACE_EDIT          1017
#define IDC_POLYGON_ANTE_EDIT           1018
#define IDC_POLYGON_RX_length_EDIT      1018
#define IDC_EDIT_WAVEFORM               1019
#define IDC_POLYGON_WAVEFORM_EDIT       1019
#define IDC_POLYGON_RX_WIDTH_EDIT       1019
#define IDC_EDIT_ANTE                   1020
#define IDC_POLYGON_RX_HEIGHT_EDIT      1020
#define IDC_POLYGON_POWER_EDIT          1021
#define IDC_POLYGON_RX_SPACE_EDIT       1021
#define IDC_POLYGON_CARRIERFRE_EDIT     1022
#define IDC_EDIT1                       1022
#define IDC_POLYGON_length_EDIT         1023
#define IDC_POLYGON_WIDTH_EDIT          1024
#define IDC_Density                     1024
#define IDC_Describe                    1026
#define IDC_EDIT_LAT                    1029
#define IDC_EDIT_ANGLE                  1030
#define IDC_EDIT_ALLOWLOSS              1031
#define IDC_EDIT_TIME                   1032
#define ID_PROJECT_NEW                  32771
#define ID_PROJECT_OPEN                 32772
#define ID_PROJECT_SAVE                 32773
#define ID_PROJECT_CLOSE                32774
#define ID_FILE_DXF                     32775
#define ID_FILE_CITY                    32776
#define ID_FILE_IMG                     32777
#define ID_IMG_JPG                      32778
#define ID_IMG_TIF                      32779
#define ID_IMG_BMP                      32780
#define ID_FILE_TIN                     32781
#define ID_FILE_DEM                     32782
#define ID_VIEW_RENDER                  32783
#define ID_VIEW_NORMAL                  32784
#define ID_SET_TRANSMMITS               32785
#define ID_TRANSMMITS_POINTS            32786
#define ID_TRANSMMITS_POLYGONS          32787
#define ID_TRANSMMITS_CIRCLE            32788
#define ID_SET_RECEIVERS                32789
#define ID_RECEIVERS_POINTS             32790
#define ID_RECEIVERS_POLYGONS           32791
#define ID_RECEIVERS_CIRCLE             32792
#define ID_SET_ANTENNA                  32793
#define ID_SET_WAVEFORM                 32794
#define ID_VIEW                         32795
#define ID_VIEW_PROJECTVIEW             32796
#define ID_EDIT                         32797
#define ID_OUTPUT                       32798
#define ID_HELP32799                    32799
#define ID_TEST                         32800
#define ID_OUTPUT32801                  32801
#define ID_OUTPUT_POWERPATH             32802
#define ID_OUTPUT_RENDEROUTPUT          32803
#define ID_CLEAR_POLYGONTX              32804
#define ID_CLEAR_POLYGONRX              32805
#define ID_EXAMPLE_PATHEXAMPLE          32806
#define ID_EXAMPLE_RENDEREXAMPLE        32807
#define ID_Menu                         32808
#define ID_HELP_ABOUT                   32809
#define ID_EDIT32810                    32810
#define ID_EDIT_TIN                     32811
#define ID_EDIT_MODELTIN                32812
#define ID_CLEAR_TIN                    32813
#define ID_CLEAR_PATH                   32814
#define ID_CLEAR_POINTTX                32815
#define ID_CLEAR_POINTRX                32816
#define ID_CLEAR_RENDER                 32817
#define ID_TEST_TEST1                   32818
#define ID_VIEW_32819                   32819
#define ID_EDIT_TIN32820                32820
#define ID_CLEAR_ALL                    32821
#define ID_SET_ENVIRONMENT              32822
#define ID_TEST_RANGE                   32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
